/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_nihao_MainActivity */

#ifndef _Included_com_example_nihao_MainActivity
#define _Included_com_example_nihao_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_nihao_MainActivity
 * Method:    GetTest
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_nihao_MainActivity_GetTest
  (JNIEnv *, jobject);

/*
 * Class:     com_example_nihao_MainActivity
 * Method:    GetNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_nihao_MainActivity_GetNumber
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
